apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "10"
  name: test-kafka-consumer
  namespace: {{ .Values.namespace }}  
spec:
  template:
    metadata:
      name: test-kafka-consumer
    spec:
     restartPolicy: Never
     serviceAccountName: kafka-tests
     containers:
     - name: test-kafka-consumer
       image: quay.io/openshift/origin-cli:4.14
       workingDir: /workspace/output
       command: ["/bin/bash", "-c"]
       args: ['oc -n ${namespace} exec -i ${cluster}-kafka-0 -- bin/kafka-console-consumer.sh --topic ${topic} --bootstrap-server ${cluster}-kafka-bootstrap:${port} --consumer.config=/config/kafka-consumer.properties --max-messages 1 | grep "${message}" || exit 1']
       env:
         - name: message
           value: {{ .Values.kafka.message }}
         - name: namespace
           value: {{ .Values.namespace }}  
         - name: cluster
           value: {{ .Values.kafka.cluster }}                      
         - name: topic
           value: {{ .Values.kafka.topic }}      
         - name: port
           value: {{ .Values.kafka.port | quote }}       
       volumeMounts:
          - name: kafka-props-tests
            readOnly: true
            mountPath: /config/kafka-consumer.properties
            subPath: kafka-consumer.properties
    volumes:
      - name: kafka-props-tests
        secret:
          secretName: kafka-props-tests
          defaultMode: 420

  backoffLimit: 0