apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "10"
  name: test-kafka-consumer
  namespace: {{ .Values.namespace }}  
spec:
  template:
    metadata:
      name: test-kafka-consumer
    spec:
      restartPolicy: Never
      serviceAccountName: kafka-tests
      containers:
      - name: test-kafka-consumer
        image: registry.redhat.io/amq-streams/kafka-36-rhel8@sha256:8b10bfb697b48ba3ed246fb846384f4cc67f05f670e9521edf0f47f829869404
        command:
          - /bin/sh
          - '-c'
          - >-
            /opt/kafka/bin/kafka-console-consumer.sh --topic ${topic} --bootstrap-server ${cluster}-kafka-bootstrap:${port} --max-messages 1 | grep "${message}" || exit 1
        env:
          - name: message
            value: {{ .Values.kafka.message }}
          - name: namespace
            value: {{ .Values.namespace }}  
          - name: cluster
            value: {{ .Values.kafka.cluster }}                      
          - name: topic
            value: {{ .Values.kafka.topic }}      
          - name: port
            value: {{ .Values.kafka.port | quote }}       
  backoffLimit: 0