apiVersion: v1
kind: Secret
metadata:
  name: kafka-props-tests
stringData:

  # This is an example: replace the values with the values aligned to the target cluster and authentication method.

  kafka-producer.properties: |-
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=SCRAM-SHA-512
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-sec-user" password="{{ .Values.kafka.password }}";
  kafka-consumer.properties: |-
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=SCRAM-SHA-512
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-sec-user" password="{{ .Values.kafka.password }}";

