apiVersion: v1
data:
  password: {{ .Values.kafka.password | b64enc | quote }}
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
  name: kafka-sec-user
  namespace: {{ .Values.namespace }}
type: Opaque