apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-sec-user
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.cluster }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"    
spec:
  authentication:
    type: SCRAM-SHA-512
    password:
      valueFrom:
        secretKeyRef:
          name: kafka-sec-pass
          key: password
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: {{ .Values.kafka.topic | quote }}
          patternType: prefix
        operations: 
          - "All"
        host: "*"
