---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-discounts-helm
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  source:
    repoURL: https://github.com/davidseve/amq-streams-testing.git
    targetRevision: HEAD
    path: ./chart        
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
